version: 0.2

phases:
  install:
    commands:
      - echo installing packages
      - yarn install
  pre_build:
    commands:
      - echo running prebuild
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the source code
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`